import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { cp, mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it, onTestFinished } from "vitest";
import { assemblePluginLayout } from "../scripts/build-layout.mjs";
import { syncCatalog } from "../scripts/sync-catalog.mjs";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const branch = "feat/langfuse-observability";
const pluginManifest = JSON.parse(
  readFileSync(join(repoRoot, ".zcode-plugin/plugin.json"), "utf8"),
) as { name: string; version: string };
const silentLog = () => {};

function git(dir: string, args: string[]): string {
  return execFileSync("git", args, { cwd: dir, encoding: "utf8" }).trim();
}

async function tempDir(prefix: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), prefix));
  onTestFinished(() => rm(dir, { recursive: true, force: true }));
  return dir;
}

async function makeLayout(): Promise<string> {
  const sourceRoot = await tempDir("zcode-sync-src-");
  for (const relativePath of [
    ".zcode-plugin/plugin.json",
    "hooks/hooks.json",
    "README.md",
    "README.zh-CN.md",
    "LICENSE",
    "THIRD_PARTY_NOTICES.md",
    "package.json",
  ]) {
    const destination = join(sourceRoot, relativePath);
    await mkdir(join(destination, ".."), { recursive: true });
    await cp(join(repoRoot, relativePath), destination);
  }
  const outputRoot = join(sourceRoot, "dist");
  await assemblePluginLayout({ sourceRoot, outputRoot });
  const runtimeEntry = join(
    outputRoot,
    "plugins",
    "zcode-plugin-langfuse",
    "dist",
    "hooks",
    "entry.mjs",
  );
  await mkdir(join(runtimeEntry, ".."), { recursive: true });
  await writeFile(runtimeEntry, "// Generated by npm run build\nexport {};\n");
  return outputRoot;
}

async function makeFork(): Promise<string> {
  const dir = await tempDir("zcode-sync-fork-");
  execFileSync("git", ["init", "-q", "-b", "main", dir]);
  git(dir, ["config", "user.email", "test@example.com"]);
  git(dir, ["config", "user.name", "Catalog Test"]);

  const catalog = {
    name: "zcode-plugins",
    owner: { name: "Z.ai", url: "https://z.ai" },
    plugins: [
      {
        name: "other-plugin",
        source: "./plugins/other-plugin",
        version: "1.0.0",
        category: "developer-tools",
      },
      {
        name: "zcode-plugin-langfuse",
        source: "./plugins/zcode-plugin-langfuse",
        version: "0.1.0",
        category: "developer-tools",
      },
    ],
  };
  await writeFile(
    join(dir, "marketplace.json"),
    `${JSON.stringify(catalog, null, 2)}\n`,
  );
  const otherReadme = join(dir, "plugins/other-plugin/README.md");
  await mkdir(join(otherReadme, ".."), { recursive: true });
  await writeFile(otherReadme, "# other-plugin\n");

  git(dir, ["add", "."]);
  git(dir, ["commit", "-m", "init catalog"]);
  git(dir, ["checkout", "-q", "-b", branch]);
  return dir;
}

describe("sync-catalog", () => {
  it("dry-run validates and plans without touching the fork", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();
    const headBefore = git(fork, ["rev-parse", "HEAD"]);
    const catalogBefore = await readFile(
      join(fork, "marketplace.json"),
      "utf8",
    );

    const result = await syncCatalog({
      layoutRoot: layout,
      repo: fork,
      dryRun: true,
      log: silentLog,
    });

    expect(result).toMatchObject({
      dryRun: true,
      changed: null,
      pushed: false,
    });
    expect(git(fork, ["rev-parse", "HEAD"])).toBe(headBefore);
    expect(git(fork, ["status", "--porcelain"])).toBe("");
    expect(existsSync(join(fork, "plugins/zcode-plugin-langfuse"))).toBe(false);
    expect(await readFile(join(fork, "marketplace.json"), "utf8")).toBe(
      catalogBefore,
    );
  });

  it("syncs the layout, replaces the stale entry, and commits the version", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();

    const result = await syncCatalog({
      layoutRoot: layout,
      repo: fork,
      log: silentLog,
    });

    expect(result).toMatchObject({
      dryRun: false,
      changed: true,
      pushed: false,
    });
    expect(result.commit).toMatch(/^[0-9a-f]+$/);
    expect(git(fork, ["log", "-1", "--format=%s"])).toBe(
      `chore(catalog): sync ${pluginManifest.name} v${pluginManifest.version}`,
    );
    expect(
      existsSync(
        join(fork, "plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs"),
      ),
    ).toBe(true);

    const catalog = JSON.parse(
      await readFile(join(fork, "marketplace.json"), "utf8"),
    ) as { plugins: Array<{ name: string; version: string }> };
    const entry = catalog.plugins.find(
      (candidate) => candidate.name === "zcode-plugin-langfuse",
    );
    expect(entry?.version).toBe(pluginManifest.version);
    expect(catalog.plugins.some((p) => p.name === "other-plugin")).toBe(true);
    expect(git(fork, ["status", "--porcelain"])).toBe("");
  });

  it("force-tracks the bundle even when the fork gitignores dist/", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();
    await writeFile(join(fork, ".gitignore"), "dist/\n");
    git(fork, ["add", ".gitignore"]);
    git(fork, ["commit", "-m", "ignore dist"]);

    const result = await syncCatalog({
      layoutRoot: layout,
      repo: fork,
      log: silentLog,
    });

    expect(result).toMatchObject({ changed: true });
    const trackedBundle = git(fork, [
      "ls-files",
      "--",
      "plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs",
    ]).trim();
    expect(trackedBundle).toBe(
      "plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs",
    );
    expect(git(fork, ["show", "--stat", "--format=", "HEAD"])).toContain(
      "plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs",
    );
  });

  it("re-adds layout files whose tracking was lost in the fork", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();
    await writeFile(join(fork, ".gitignore"), "dist/\n");
    git(fork, ["add", ".gitignore"]);
    git(fork, ["commit", "-m", "ignore dist"]);
    await syncCatalog({ layoutRoot: layout, repo: fork, log: silentLog });

    git(fork, [
      "rm",
      "-q",
      "--cached",
      "plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs",
    ]);
    git(fork, ["commit", "-m", "drop bundle from index"]);

    const result = await syncCatalog({
      layoutRoot: layout,
      repo: fork,
      log: silentLog,
    });

    expect(result).toMatchObject({ changed: true });
    expect(
      git(fork, [
        "ls-files",
        "--",
        "plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs",
      ]).trim(),
    ).toBe("plugins/zcode-plugin-langfuse/dist/hooks/entry.mjs");
  });

  it("is a no-op when the fork already matches the layout", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();
    await syncCatalog({ layoutRoot: layout, repo: fork, log: silentLog });
    const headAfterFirst = git(fork, ["rev-parse", "HEAD"]);

    const result = await syncCatalog({
      layoutRoot: layout,
      repo: fork,
      log: silentLog,
    });

    expect(result).toMatchObject({ changed: false, commit: null });
    expect(git(fork, ["rev-parse", "HEAD"])).toBe(headAfterFirst);
  });

  it("refuses a dirty fork with recovery guidance", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();
    await writeFile(join(fork, "uncommitted.txt"), "dirty\n");

    await expect(
      syncCatalog({ layoutRoot: layout, repo: fork, log: silentLog }),
    ).rejects.toThrow(/not clean/i);
    expect(existsSync(join(fork, "plugins/zcode-plugin-langfuse"))).toBe(false);
  });

  it("refuses a missing layout before touching the fork", async () => {
    const fork = await makeFork();
    const missingLayout = join(
      await tempDir("zcode-sync-empty-"),
      "plugin-layout",
    );

    await expect(
      syncCatalog({ layoutRoot: missingLayout, repo: fork, log: silentLog }),
    ).rejects.toThrow(/Plugin layout not found/);
  });

  it("pushes the sync commit to a local remote with --push", async () => {
    const layout = await makeLayout();
    const fork = await makeFork();
    const remote = join(await tempDir("zcode-sync-remote-"), "remote.git");
    execFileSync("git", ["init", "-q", "--bare", "-b", "main", remote]);
    git(fork, ["remote", "add", "origin", remote]);
    git(fork, ["push", "-q", "origin", branch]);

    const result = await syncCatalog({
      layoutRoot: layout,
      repo: fork,
      push: true,
      log: silentLog,
    });

    expect(result).toMatchObject({ changed: true, pushed: true });
    const remoteHead = execFileSync(
      "git",
      ["--git-dir", remote, "rev-parse", branch],
      { encoding: "utf8" },
    ).trim();
    expect(remoteHead).toBe(git(fork, ["rev-parse", "HEAD"]));
  });
});
