import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { validatePluginRoot } from "../scripts/build-layout.mjs";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";
const pluginManifest = JSON.parse(
  readFileSync(join(repoRoot, ".zcode-plugin/plugin.json"), "utf8"),
) as { name: string; version: string };
const distRoot = join(repoRoot, "dist");
const runtimeEntry = join(distRoot, "payload", "dist", "hooks", "entry.mjs");

function packagePlugin() {
  execFileSync(npmCommand, ["run", "package:plugin"], {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: "pipe",
  });
}

describe("unified plugin package", () => {
  it("builds dist as the official-layout plugin root", () => {
    packagePlugin();

    const expectedFiles = [
      ".zcode-plugin/plugin.json",
      "hooks/hooks.json",
      "payload/dist/hooks/entry.mjs",
      "marketplace.json",
      "package.json",
      "README.md",
      "README_CN.md",
      "LICENSE",
      "THIRD_PARTY_NOTICES.md",
    ];
    for (const relativePath of expectedFiles) {
      expect(existsSync(join(distRoot, relativePath))).toBe(true);
    }

    const marketplace = JSON.parse(
      readFileSync(join(distRoot, "marketplace.json"), "utf8"),
    ) as {
      plugins: Array<{ name: string; source: string; version: string }>;
    };
    expect(marketplace.plugins[0]).toMatchObject({
      name: pluginManifest.name,
      version: pluginManifest.version,
    });

    const hooks = JSON.parse(
      readFileSync(join(distRoot, "hooks/hooks.json"), "utf8"),
    ) as { hooks: Record<string, Array<{ hooks: Array<{ args: string[] }> }>> };
    for (const event of Object.keys(hooks.hooks)) {
      const args = hooks.hooks[event]?.[0]?.hooks?.[0]?.args ?? [];
      expect(args[0]).toContain("payload/dist/hooks/entry.mjs");
    }

    const bundle = readFileSync(runtimeEntry, "utf8");
    expect(bundle).toContain("Generated by npm run build");

    expect(existsSync(join(repoRoot, "src/hooks/entry.ts"))).toBe(true);
  });

  it("fails validation when the payload entry is missing", async () => {
    await expect(validatePluginRoot(repoRoot)).rejects.toThrow(
      /payload\/dist\/hooks\/entry.mjs/,
    );
  });

  it("removes stale files on a repeated build", () => {
    const stalePath = join(distRoot, "stale-from-previous-build.txt");
    writeFileSync(stalePath, "stale\n");

    packagePlugin();

    expect(existsSync(stalePath)).toBe(false);
  });
});
