import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { validatePluginRoot } from "../scripts/build-layout.mjs";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";
const pluginManifest = JSON.parse(
  readFileSync(join(repoRoot, ".zcode-plugin/plugin.json"), "utf8"),
) as { name: string; version: string };
const distRoot = join(repoRoot, "dist");
const pluginDir = join(distRoot, "plugins", pluginManifest.name);
const runtimeEntry = join(pluginDir, "hooks", "entry.mjs");

function packagePlugin() {
  execFileSync(npmCommand, ["run", "package:plugin"], {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: "pipe",
  });
}

describe("unified plugin package", () => {
  it("builds dist as a marketplace shell with the official-layout plugin", () => {
    packagePlugin();

    const expectedPluginFiles = [
      ".zcode-plugin/plugin.json",
      ".claude-plugin/plugin.json",
      "hooks/hooks.json",
      "hooks/entry.mjs",
      "README.md",
      "README_CN.md",
      "LICENSE",
      "THIRD_PARTY_NOTICES.md",
    ];
    for (const relativePath of expectedPluginFiles) {
      expect(existsSync(join(pluginDir, relativePath))).toBe(true);
    }
    expect(existsSync(join(distRoot, "marketplace.json"))).toBe(true);
    expect(existsSync(join(pluginDir, "package.json"))).toBe(false);
    expect(existsSync(join(pluginDir, "marketplace.json"))).toBe(false);
    expect(existsSync(join(pluginDir, "payload"))).toBe(false);

    const marketplace = JSON.parse(
      readFileSync(join(distRoot, "marketplace.json"), "utf8"),
    ) as {
      plugins: Array<{ name: string; source: string; version: string }>;
    };
    expect(marketplace.plugins[0]).toMatchObject({
      name: pluginManifest.name,
      source: `./plugins/${pluginManifest.name}`,
      version: pluginManifest.version,
    });

    const hooks = JSON.parse(
      readFileSync(join(pluginDir, "hooks/hooks.json"), "utf8"),
    ) as { hooks: Record<string, Array<{ hooks: Array<{ args: string[] }> }>> };
    for (const event of Object.keys(hooks.hooks)) {
      const args = hooks.hooks[event]?.[0]?.hooks?.[0]?.args ?? [];
      expect(args[0]).toContain("${ZCODE_PLUGIN_ROOT}/hooks/entry.mjs");
    }

    const claudeManifest = JSON.parse(
      readFileSync(join(pluginDir, ".claude-plugin/plugin.json"), "utf8"),
    );
    const zcodeManifest = JSON.parse(
      readFileSync(join(pluginDir, ".zcode-plugin/plugin.json"), "utf8"),
    );
    expect(claudeManifest).toEqual(zcodeManifest);

    const bundle = readFileSync(runtimeEntry, "utf8");
    expect(bundle).toContain("Generated by npm run build");

    expect(existsSync(join(repoRoot, "src/hooks/entry.ts"))).toBe(true);
  });

  it("runs the built bundle as a fail-open Stop hook", () => {
    packagePlugin();
    const dataDir = mkdtempSync(join(tmpdir(), "lf-hook-smoke-"));
    try {
      const env: NodeJS.ProcessEnv = { ...process.env };
      for (const key of Object.keys(env)) {
        if (key.startsWith("LANGFUSE_")) delete env[key];
      }
      env.ZCODE_PLUGIN_DATA = dataDir;
      env.ZCODE_CONFIG_PATH = join(dataDir, "no-config.json");
      const stdout = execFileSync(
        process.execPath,
        [runtimeEntry],
        {
          input: `${JSON.stringify({
            hook_event_name: "Stop",
            session_id: "vitest-smoke",
            last_assistant_message: "ok",
          })}\n`,
          env,
          encoding: "utf8",
        },
      );
      expect(JSON.parse(stdout)).toEqual({});
      expect(readdirSync(dataDir, { recursive: true })).toEqual([]);
    } finally {
      rmSync(dataDir, { recursive: true, force: true });
    }
  });

  it.runIf(process.platform !== "win32")("packages the shell into the release zip shape", () => {
    packagePlugin();
    const zipDir = mkdtempSync(join(tmpdir(), "lf-zip-shape-"));
    try {
      const zipPath = join(zipDir, "release.zip");
      execFileSync("zip", ["-r", "-X", zipPath, "marketplace.json", "plugins"], {
        cwd: distRoot,
      });
      const names = execFileSync("unzip", ["-Z1", zipPath], {
        encoding: "utf8",
      })
        .split("\n")
        .filter((line) => line && !line.endsWith("/"))
        .sort();
      expect(names).toEqual(
        [
          "marketplace.json",
          `plugins/${pluginManifest.name}/.claude-plugin/plugin.json`,
          `plugins/${pluginManifest.name}/.zcode-plugin/plugin.json`,
          `plugins/${pluginManifest.name}/LICENSE`,
          `plugins/${pluginManifest.name}/README.md`,
          `plugins/${pluginManifest.name}/README_CN.md`,
          `plugins/${pluginManifest.name}/THIRD_PARTY_NOTICES.md`,
          `plugins/${pluginManifest.name}/hooks/entry.mjs`,
          `plugins/${pluginManifest.name}/hooks/hooks.json`,
        ].sort(),
      );
      const shell = execFileSync("unzip", ["-p", zipPath, "marketplace.json"], {
        encoding: "utf8",
      });
      expect(shell).toContain(`./plugins/${pluginManifest.name}`);
    } finally {
      rmSync(zipDir, { recursive: true, force: true });
    }
  });

  it("fails validation when the bundled entry is missing", async () => {
    packagePlugin();
    rmSync(runtimeEntry);

    await expect(validatePluginRoot(distRoot)).rejects.toThrow(
      /hooks\/entry\.mjs/,
    );
  });

  it("removes stale files on a repeated build", () => {
    const stalePath = join(pluginDir, "stale-from-previous-build.txt");
    writeFileSync(stalePath, "stale\n");

    packagePlugin();

    expect(existsSync(stalePath)).toBe(false);
  });
});
