import { mkdir, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { assemblePluginLayout, validatePluginLayout } from "./build-layout.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");

// dist/ is structured as a ZCode marketplace root:
//   dist/marketplace.json
//   dist/plugins/<name>/…            (the installable plugin, incl. its own dist/)
await rm(dist, { recursive: true, force: true });
const layout = await assemblePluginLayout({
  sourceRoot: root,
  outputRoot: dist,
});

const runtimeEntry = resolve(
  layout.pluginRoot,
  "dist",
  "hooks",
  "entry.mjs",
);
await mkdir(resolve(runtimeEntry, ".."), { recursive: true });

await build({
  absWorkingDir: root,
  entryPoints: ["src/hooks/entry.ts"],
  outfile: `dist/plugins/${layout.name}/dist/hooks/entry.mjs`,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  sourcemap: false,
  legalComments: "eof",
  banner: {
    js: "// Generated by npm run build. Edit src/, not dist/.",
  },
});

await validatePluginLayout({ outputRoot: dist });

process.stdout.write(
  `Built ${layout.name}@${layout.version} → dist/ (marketplace layout)\n`,
);
