import { cp, mkdir, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { validatePluginRoot } from "./build-layout.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");
const runtimeEntry = resolve(dist, "payload", "dist", "hooks", "entry.mjs");

// dist/ is assembled as the official-layout plugin root:
//   dist/.zcode-plugin/plugin.json
//   dist/hooks/hooks.json          (points into payload/)
//   dist/payload/dist/hooks/entry.mjs   (the sealed bundle, mimosa-style)
//   dist/marketplace.json          (so the extracted dir is add-able as a market)
//   dist/README.md, README_CN.md, LICENSE, THIRD_PARTY_NOTICES.md, package.json
await rm(dist, { recursive: true, force: true });

for (const relativePath of [
  ".zcode-plugin",
  "hooks",
  "README.md",
  "LICENSE",
  "THIRD_PARTY_NOTICES.md",
  "package.json",
  "marketplace.json",
]) {
  await cp(resolve(root, relativePath), resolve(dist, relativePath), {
    recursive: true,
  });
}

await cp(resolve(root, "README.zh-CN.md"), resolve(dist, "README_CN.md"));

await mkdir(dirname(runtimeEntry), { recursive: true });

await build({
  absWorkingDir: root,
  entryPoints: ["src/hooks/entry.ts"],
  outfile: `dist/payload/dist/hooks/entry.mjs`,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  sourcemap: false,
  legalComments: "eof",
  banner: {
    js: "// Generated by npm run build. Edit src/, not dist/.",
  },
});

const layout = await validatePluginRoot(dist);

process.stdout.write(
  `Built ${layout.name}@${layout.version} → dist/ (official plugin layout)\n`,
);
